### ISSUE TITLE
Suggestion - Expand on Azure Web App Service

### ISSUE THREAD

**Issue by mormond** [martinkearn/Web-Performance-and-Compatibility-Lab#2]
"This is very easy to do with Azure Web App Service and the source integration feature, you simply commit to GitHub, VSO or whatever source control system you are using and the site gets deployed"

it would be helpful to expand this a little to explain the quickest / simplest way to do this if I have / don't have an Azure subscription. Can I use the "try it" feature at the link you've mentioned? If so, which options should I select? If not, say so. If I have an Azure subscription do I just create a new web app service and then hook that to GitHub / VSO via the Azure portal? Just a little bit of guidance to point me in the right direction would be helpful.

**Comment by martinkearn** [comment]
Thanks Mike. I've had this feedback from elsewhere too. It has now been addressed and there is an optional exercise referenced in the 'Setup' document about Azure setup: https://github.com/martinkearn/Web-Performance-and-Compatibility-Lab/blob/master/AzureSetup.md
